[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RTDT Read The Docs Tutorial"
authors = [{name = "André Luís", email = "de.de@discente.ufg.br"}]
dynamic = ["version", "description"]
